# Generated by Django 5.1.4 on 2024-12-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Livre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date_publication', models.DateField()),
                ('genre', models.CharField(choices=[('F', 'Fiction'), ('NF', 'Non-Fiction'), ('SF', 'Science Fiction'), ('FAN', 'Fantasy'), ('MYS', 'Mystery'), ('ROM', 'Romance'), ('HOR', 'Horror'), ('BIO', 'Biography'), ('HIS', 'History'), ('SEL', 'Self-Help')], max_length=3)),
                ('disponible', models.BooleanField(default=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livres', to='biblio.auteur')),
            ],
        ),
    ]
